# Configuration file for Dependabot (https://github.com/dependabot)

version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  open-pull-requests-limit: 1
  schedule:
    interval: daily
    time: "03:00"
  labels:
  - ci/cd
  - dependencies
- package-ecosystem: gomod
  directory: /
  open-pull-requests-limit: 1
  schedule:
    interval: daily
    time: "03:00"
  labels:
  - dependencies
